name: Python

on:
  push:
  release:
    types: [published]
  pull_request_target:
    branches: [ "main" ]

jobs:

  build:
    strategy:
      matrix:
        runner: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - name: Check out PR branch code
      if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify your Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt file

    - name: Build/Package
      run: |
        python setup.py sdist bdist_wheel # Assuming you have setup.py for packaging
        tar -zcf your-python-project.tar.gz dist/  # Change 'your-python-project' as needed

    - uses: actions/upload-artifact@v3
      with:
        name: your-python-project-${{ matrix.runner }}
        path: your-python-project.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release'
    steps:
    - name: Check out code
      if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: your-python-project-${{ matrix.runner }}
      
    - name: Upload
      uses: viamrobotics/upload-module@main
      with:
        module-path: your-python-project.tar.gz
        # Add other necessary fields as per your requirement
